#!/bin/sh

LD_LIBRARY_PATH=../../lib:../../lib/.libs:$LD_LIBRARY_PATH
# cater for Mac OS
DYLD_LIBRARY_PATH=../../lib:../../lib/.libs:$DYLD_LIBRARY_PATH
GUILE_LOAD_PATH=../..:$GUILE_LOAD_PATH
GUILE_LOAD_COMPILED_PATH=../..:$GUILE_LOAD_COMPILED_PATH
export LD_LIBRARY_PATH DYLD_LIBRARY_PATH GUILE_LOAD_PATH GUILE_LOAD_COMPILED_PATH 
guile $1
