@node await ports,monotonic time,event loop,Top

The (a-sync await-ports) module provides procedures for using
guile-2.2's suspendable ports with event loops, and a convenient way
of using ports' normal input and output procedures with non-blocking
ports.

Including this module will automatically enable suspendable ports.  To
disable them again, the uninstall-suspendable-ports! procedure can be
called, but this means that these procedures can no longer be used
while suspendable ports are disabled.  In addition, any port using
these procedures must be made non-blocking using fcntl as follows:

@example
(fcntl [port] F_SETFL (logior O_NONBLOCK
                      (fcntl [port] F_GETFL)))
@end example

@deffn {Scheme Procedure} await-read-suspendable! await resume [loop] port proc
This procedure is provided to implement read file watches using
guile-2.2's suspendable ports.  'proc' is a procedure taking a single
argument, to which the port will be passed when it is invoked, and is
intended to use the port's normal read procedures.  'port' must be a
suspendable non-blocking port.  'proc' will be executed whenever there
is something available to read, and this procedure will return when
'proc' returns, as if by a blocking read.  The event loop will not be
blocked by this procedure even if only individual characters or bytes
comprising part characters are available at any one time.  It is
intended to be called in a waitable procedure invoked by a-sync.  If
an exceptional condition ('excpt) is encountered by the
implementation, #f will be returned by this procedure and the read
operations to be performed by 'proc' will be abandonned; there is
however no guarantee that any exceptional condition that does arise
will be encountered by the implementation - the user procedure 'proc'
may get there first and deal with it, or it may not.  However
exceptional conditions are very rare, usually comprising only
out-of-band data on a TCP socket, or a pseudoterminal master in packet
mode seeing state change in a slave.

The 'loop' argument is optional: this procedure operates on the event
loop passed in as an argument, or if none is passed (or #f is passed),
on the default event loop.

This procedure must (like the a-sync procedure) be called in the same
thread as that in which the event loop runs.

Exceptions (say, from 'proc' because of port or conversion errors)
will propagate out of this procedure in the first instance, and if not
caught locally will then propagate out of event-loop-run!.

As an example of how to use await-read-suspendable!, here is the
implementation of await-getline!:

@example
(define await-getline!
  (case-lambda
    ((await resume port)
     (await-getline! await resume #f port))
    ((await resume loop port)
     (await-read-suspendable! await resume loop port
			      (lambda (p)
				(read-line p))))))
@end example
@end deffn

@deffn {Scheme Procedure} await-getline! await resume [loop] port
This procedure is provided mainly to retain compatibility with the
guile-a-sync library for guile-2.0, because it is trivial to implement
with await-read-suspendable! (and is implemented by
await-read-suspendable!).

It is intended to be called in a waitable procedure invoked by a-sync,
and reads a line of text from a non-blocking suspendable port and
returns it (without the terminating '\n' character).  The 'loop'
argument is optional: this procedure operates on the event loop passed
in as an argument, or if none is passed (or #f is passed), on the
default event loop.  If an exceptional condition ('excpt) is
encountered by the implementation, #f will be returned by this
procedure and the read operations to be performed by 'proc' will be
abandonned.  See the documentation on the await-read-suspendable!
procedure for further particulars about this procedure.

Here is an example of the use of await-getline!:
@example
(set-default-event-loop!) ;; if none has yet been set
(a-sync (lambda (await resume)
	  (display "Enter a line of text at the keyboard\n")
	  (let ((port (open "/dev/tty" O_RDONLY)))
	    (fcntl port F_SETFL (logior O_NONBLOCK
				(fcntl port F_GETFL)))
	    (simple-format #t
			   "The line was: ~A\n"
			   (await-getline! await resume
					   port)))))
(event-loop-run!)
@end example
@end deffn

@deffn {Scheme Procedure} await-geteveryline! await resume [loop] port proc
This procedure is provided mainly to retain compatibility with the
guile-a-sync library for guile-2.0, because it is trivial to implement
with await-read-suspendable! (and is implemented by
await-read-suspendable!).

It is intended to be called in a waitable procedure invoked by a-sync,
and will apply 'proc' to every complete line of text received (without
the terminating '\n' character).  The watch will not end until
end-of-file or an exceptional condition ('excpt) is reached.  In the
event of that happening, this procedure will end and return an
end-of-file object or #f respectively.  The 'loop' argument is
optional: this procedure operates on the event loop passed in as an
argument, or if none is passed (or #f is passed), on the default event
loop.  See the documentation on the await-read-suspendable! procedure
for further particulars about this procedure.

Here is an example of the use of await-geteveryline! (because the
keyboard has no end-of-file, use Ctrl-C to exit this code snippet):
@example
(set-default-event-loop!) ;; if none has yet been set
(a-sync (lambda (await resume)
	(display "Enter lines of text at the keyboard, ^C to finish\n")
	  (let ((port (open "/dev/tty" O_RDONLY)))
	    (fcntl port F_SETFL (logior O_NONBLOCK
				(fcntl port F_GETFL)))
	    (await-geteveryline! await resume
				 port
				 (lambda (line)
				   (simple-format #t
						  "The line was: ~A\n"
						  line))))))
(event-loop-run!)
@end example
@end deffn

@deffn {Scheme Procedure} await-getsomelines! await resume [loop] port proc
This procedure is intended to be called in a waitable procedure
invoked by a-sync, and does the same as await-geteveryline!, except
that it provides a second argument to 'proc', namely an escape
continuation which can be invoked by 'proc' to cause the procedure to
return before end-of-file is reached.  Behavior is identical to
await-geteveryline! if the continuation is not invoked.

This procedure will apply 'proc' to every complete line of text
received (without the terminating '\n' character).  The watch will not
end until end-of-file or an exceptional condition ('excpt) is reached,
which would cause this procedure to end and return an end-of-file
object or #f respectively, or until the escape continuation is
invoked, in which case the value passed to the escape continuation
will be returned.  The 'loop' argument is optional: this procedure
operates on the event loop passed in as an argument, or if none is
passed (or #f is passed), on the default event loop.  See the
documentation on the await-read-suspendable! procedure for further
particulars about this procedure.

Here is an example of the use of await-getsomelines!:
@example
(set-default-event-loop!) ;; if none has yet been set
(a-sync (lambda (await resume)
	(display "Enter lines of text at the keyboard, enter an empty line to finish\n")
	  (let ((port (open "/dev/tty" O_RDONLY)))
	    (fcntl port F_SETFL (logior O_NONBLOCK
				(fcntl port F_GETFL)))
	    (await-getsomelines! await resume
				 port
				 (lambda (line k)
				   (when (string=? line "")
					 (k #f))
				   (simple-format #t
						  "The line was: ~A\n"
						  line))))))
(event-loop-run!)
@end example
@end deffn

@deffn {Scheme Procedure} await-write-suspendable! await resume [loop] port proc
This procedure is provided to implement write file watches using
guile-2.2's suspendable ports.  'proc' is a procedure taking a single
argument, to which the port will be passed when it is invoked, and is
intended to use the port's normal write procedures.  'port' must be a
suspendable non-blocking port.  'proc' will be executed whenever the
port is available to write to, and this procedure will return when
'proc' returns, as if by a blocking write.  The event loop will not be
blocked by this procedure even if only individual characters or bytes
comprising part characters can be written at any one time.  It is
intended to be called in a waitable procedure invoked by a-sync.  If
an exceptional condition ('excpt) is encountered by the
implementation, #f will be returned by this procedure and the write
operations to be performed by 'proc' will be abandonned; there is
however no guarantee that any exceptional condition that does arise
will be encountered by the implementation - the user procedure 'proc'
may get there first and deal with it, or it may not.  However
exceptional conditions on write ports cannot normally occur.

The 'loop' argument is optional: this procedure operates on the event
loop passed in as an argument, or if none is passed (or #f is passed),
on the default event loop.

This procedure must (like the a-sync procedure) be called in the same
thread as that in which the event loop runs.

Exceptions (say, from 'proc' because of port or conversion errors)
will propagate out of this procedure in the first instance, and if not
caught locally will then propagate out of event-loop-run!.
@end deffn
