\input texinfo
@c -*-texinfo-*-
@c %**start of header
@settitle guile-a-sync2
@setfilename guile-a-sync2.info
@c %**end of header

@ifnottex
@node Top,coroutines,,
@top guile-a-sync2 reference
@end ifnottex

This is the guile-a-sync2 library.  It provides both an asynchronous
event loop for guile-2.2, and coroutines to enable an event loop
(including other event loops such as the glib event loop) to be used
with 'await' semantics to deal with inversion of control -- otherwise
known as ``callback hell''.

The guile-a-sync library is provided in five modules:
@menu
* coroutines::     In module (a-sync coroutines) - provides coroutines for await semantics on asynchronous events
* event loop::     In module (a-sync event-loop) - provides an event loop for asynchronous events
* monotonic time:: In module (a-sync monotonic-time) - enables monotonic time to be used for timeouts
* gnome glib::     In module (a-sync gnome-glib) - provides some convenience await procedures for the glib main loop
* compose::        In module (a-sync compose) - provides the compose-a-sync macro interface for the a-sync coroutine
@end menu

@include coroutines.texi
@include event-loop.texi
@include monotonic-time.texi
@include gnome-glib.texi
@include compose.texi

@bye
