\input texinfo
@settitle guile-a-sync

@ifnottex
@node Top,coroutines,,

@strong{guile-a-sync}

This is the guile-a-sync library.  It provides both an asynchronous
event loop for guile, and coroutines to enable an event loop
(including other event loops such as the glib event loop) to be used
with 'await' semantics to deal with inversion of control -- otherwise
known as ``callback hell''.

@end ifnottex

The guile-a-sync library is provided in three modules:
@menu
* coroutines::     In module (async coroutines) - provides coroutines for await semantics on asynchronous events
* event loop::     In module (async event-loop) - provides an event loop for asynchronous events
* monotonic time:: In module (async monotonic-time) - enables monotonic time to be used for timeouts
@end menu

@include coroutines.texi
@include event-loop.texi
@include monotonic-time.texi

@bye
