\input texinfo
@c -*-texinfo-*-
@c %**start of header
@settitle guile-a-sync2
@setfilename guile-a-sync2.info
@c %**end of header

@ifnottex
@node Top,overview,,
@top guile-a-sync2 reference
@end ifnottex

This is the guile-a-sync2 library.  It provides both an asynchronous
event loop for guile-2.2, and coroutines to enable an event loop
(including other event loops such as the glib event loop) to be used
with 'await' semantics to deal with inversion of control -- otherwise
known as ``callback hell''.

@menu
General overview
* overview::       General overview of the operation of the library

Modules
* coroutines::     (a-sync coroutines) module - provides coroutines for await semantics on asynchronous events
* event loop::     (a-sync event-loop) module - provides an event loop for asynchronous events
* await ports::    (a-sync await-ports) module - provides procedures for suspendable ports
* thread pool::    (a-sync thread-pool) module - provides a thread pool with asychonous procedures
* monotonic time:: (a-sync monotonic-time) module - enables monotonic time to be used for timeouts
* gnome glib::     (a-sync gnome-glib) module - provides some convenience await procedures for the glib main loop
* compose::        (a-sync compose) module - provides the compose-a-sync macro interface for the a-sync coroutine
* meeting::        (a-sync meeting) module - provides for synchronization between a-sync or compose-a-sync blocks
@end menu

@include overview.texi
@include coroutines.texi
@include event-loop.texi
@include await-ports.texi
@include thread-pool.texi
@include monotonic-time.texi
@include gnome-glib.texi
@include compose.texi
@include meeting.texi

@bye
